import { ButtonHTMLAttributes } from 'react';
import { ForwardRefExoticComponent } from 'react';
import { HTMLAttributes } from 'react';
import { ImgHTMLAttributes } from 'react';
import { Paths } from 'type-fest';
import { RefAttributes } from 'react';
import { TooltipRefProps } from 'react-tooltip';

export declare const Breadcrumb: ForwardRefExoticComponent<HTMLAttributes<HTMLElement> & {
    breadcrumbs?: {
        href: string;
        text: string;
    }[];
} & RefAttributes<HTMLElement>>;

export declare const Button: ForwardRefExoticComponent<ButtonHTMLAttributes<HTMLButtonElement> & {
    disabled?: boolean;
    iconLeft?: IconProp;
    iconRight?: IconProp;
    loading?: boolean;
    variant?: "primary" | "secondary" | "secondary-white" | "tertiary" | "tertiary-transparent";
} & RefAttributes<HTMLButtonElement>>;

export declare const CategoryButton: ForwardRefExoticComponent<ButtonHTMLAttributes<HTMLButtonElement> & {
    active?: boolean;
    color?: "white" | "grey";
    size?: "large" | "small";
} & RefAttributes<HTMLButtonElement>>;

export declare const Checkbox: ForwardRefExoticComponent<HTMLAttributes<HTMLDivElement> & {
    error?: React.ReactNode;
    inputProps?: React.InputHTMLAttributes<HTMLInputElement>;
} & RefAttributes<HTMLDivElement>>;

export declare const Icon: ForwardRefExoticComponent<ImgHTMLAttributes<HTMLImageElement> & {
    icon?: IconPath;
} & RefAttributes<HTMLImageElement>>;

declare type IconPath = Exclude<Paths<typeof icons>, "carrier" | "flag" | "functional" | "payment" | "social" | "support">;

declare type IconProp = React.ComponentProps<typeof Icon>["icon"] | React.ReactElement;

declare type IconProp_2 = React.ComponentProps<typeof Icon>["icon"];

declare const icons: {
    carrier: {
        brt: string;
        celeritas: string;
        chronopost: string;
        colissimo: string;
        dhlexpress: string;
        dhlpost: string;
        dpd: string;
        fedexexpress: string;
        fedex: string;
        gls: string;
        hermes: string;
        postat: string;
        postnl: string;
        postnord: string;
        seur2: string;
        seur: string;
        swisspost: string;
        ups: string;
    };
    flag: {
        ad: string;
        ae: string;
        at: string;
        au: string;
        ax: string;
        ba: string;
        be: string;
        bg: string;
        ca: string;
        ch: string;
        cl: string;
        cn: string;
        cy: string;
        cz: string;
        de: string;
        dk: string;
        ee: string;
        es: string;
        fi: string;
        fr: string;
        gb: string;
        gg: string;
        gi: string;
        gl: string;
        gr: string;
        hk: string;
        hr: string;
        hu: string;
        ic: string;
        ie: string;
        il: string;
        im: string;
        is: string;
        it: string;
        je: string;
        jp: string;
        kr: string;
        lt: string;
        lu: string;
        lv: string;
        mc: string;
        me: string;
        mk: string;
        mt: string;
        nl: string;
        no: string;
        nx: string;
        nz: string;
        pl: string;
        pt: string;
        ro: string;
        rs: string;
        se: string;
        sg: string;
        si: string;
        sk: string;
        us: string;
        za: string;
    };
    functional: {
        accountDefaultBlack: string;
        amazonbuttonFilledGrey: string;
        arrowdownDefaultBlack: string;
        arrowdownDefaultGrey: string;
        arrowdownDefaultWhite: string;
        arrowdownFilledBlack: string;
        arrowdownFilledGrey: string;
        arrowdownFilledWhite: string;
        arrowleftDefaultBlack: string;
        arrowleftDefaultGrey: string;
        arrowleftDefaultWhite: string;
        arrowleftFilledBlack: string;
        arrowleftFilledGreen: string;
        arrowleftFilledGrey: string;
        arrowleftFilledWhite: string;
        arrowrectangleleftFilledBlack: string;
        arrowrectangleleftFilledGrey: string;
        arrowrectanglerightFilledBlack: string;
        arrowrectanglerightFilledGrey: string;
        arrowrightDefaultBlack: string;
        arrowrightDefaultGrey: string;
        arrowrightDefaultWhite: string;
        arrowrightFilledBlack: string;
        arrowrightFilledGreen: string;
        arrowrightFilledGrey: string;
        arrowrightFilledWhite: string;
        arrowupDefaultBlack: string;
        arrowupDefaultGrey: string;
        arrowupDefaultWhite: string;
        arrowupFilledBlack: string;
        arrowupFilledGrey: string;
        arrowupFilledWhite: string;
        attentionFilledBlack: string;
        attentionFilledRed: string;
        attentionFilledYellow: string;
        attentionOutlineBlack: string;
        attentionOutlineGrey: string;
        attentionOutlineWhite: string;
        cartDefaultBlack: string;
        cartDefaultWhite: string;
        chatbubbleDefault: string;
        chatbubbleFilledBlue: string;
        chatDefaultBlack: string;
        chatrectangleFilled: string;
        chatroundFilled: string;
        checkDefaultBlack: string;
        checkDefaultBlue: string;
        checkDefaultGreen: string;
        checkDefaultSky: string;
        checkDefaultWhite: string;
        closeDefaultBlack: string;
        closeDefaultGrey: string;
        closeDefaultWhite: string;
        closeFilledBlack: string;
        closeFilledGrey: string;
        closeFilledWhite: string;
        closeOutlineBlack: string;
        closeOutlineGrey: string;
        closeOutlineWhite: string;
        downloadDefaultBlack: string;
        downloadDefaultGrey: string;
        eyeclosedDefaultBlack: string;
        eyeclosedDefaultGrey: string;
        eyeopenDefaultBlack: string;
        eyeopenDefaultGrey: string;
        filterDefaultBlack: string;
        heartDefaultBlack: string;
        heartFilledBlack: string;
        heartFilledBlue: string;
        heartFilledGrey: string;
        heartFilledWhite: string;
        helpFilledBlack: string;
        helpFilledGreen: string;
        helpFilledWhite: string;
        homeDefaultBlack: string;
        infoOutlineBlack: string;
        infoOutlineBlue: string;
        infoOutlineGrey: string;
        infoOutlineWhite: string;
        klarnabuttonFilledGrey: string;
        klarnabuttonFilledWhite: string;
        linkFilledWhite: string;
        mailFilledBlack: string;
        mailFilledSky: string;
        menuDefaultBlack: string;
        paypalbuttonFilledGrey: string;
        paypalbuttonFilledWhite: string;
        phoneFilledBlue: string;
        photocreditFilledBlack: string;
        pinDefaultBlack: string;
        playFilledBlack: string;
        playFilledGrey: string;
        playOutlineBlack: string;
        ridercreditFilledBlack: string;
        searchDefaultBlack: string;
        searchDefaultGrey: string;
        searchDefaultWhite: string;
        shareDefaultBlack: string;
        shareDefaultWhite: string;
        smileyangryFilledBlue: string;
        smileyangryOutlineBlue: string;
        smileylikeFilledBlue: string;
        smileylikeOutlineBlue: string;
        smileyloveFilledBlue: string;
        smileyloveOutlineBlue: string;
        smileyneutralFilledBlue: string;
        smileyneutralOutlineBlue: string;
        smileyunhappyFilledBlue: string;
        smileyunhappyOutlineBlue: string;
        sortDefaultBlack: string;
        spinnerFilledBlack: string;
        spinnerFilledWhite: string;
        starFilledBlack: string;
        starFilledBlue: string;
        starhalfFilledBlue: string;
        starOutlineBlack: string;
        supportFilledBlue: string;
        thumbsupDefaultBlack: string;
        thumbsupDefaultBlue: string;
        uploadDefaultBlack: string;
        uploadDefaultGrey: string;
        zoominFilledBlack: string;
        zoominFilledWhite: string;
        zoomoutFilledBlack: string;
        zoomoutFilledWhite: string;
    };
    payment: {
        amazonpay: string;
        amazonpaydefault: string;
        americanexpress: string;
        bancaires2: string;
        bancaires: string;
        cashondelivery: string;
        creditcard: string;
        dinersclub: string;
        discover: string;
        ideal: string;
        karde: string;
        karen: string;
        karfr: string;
        karit: string;
        kar: string;
        klarnasofort: string;
        klarna: string;
        maestro: string;
        mastercardsecure: string;
        mastercard: string;
        paypaldefault: string;
        paypalexpress: string;
        paypal: string;
        prepaid: string;
        sofort2: string;
        sofort: string;
        verifiedvisa: string;
        visa: string;
    };
    social: {
        facebookDefaultBlack: string;
        facebookFilledBlue: string;
        instaDefaultBlack: string;
        instaFilled: string;
        kununuDefaultWhite: string;
        linkedinFilledBlue: string;
        pinterestDefaultBlack: string;
        pinterestDefaultRed: string;
        tiktokFilledBlack: string;
        tiktokFilledWhite: string;
        vimeoDefaultBlack: string;
        vimeoFilledBlue: string;
        whatsappDefaultBlack: string;
        whatsappDefaultBlue: string;
        whatsappDefaultWhite: string;
        whatsappFilledGreen: string;
        xingFilledWhite: string;
        youtubeDefaultBlack: string;
        youtubeFilledRed: string;
    };
    support: {
        arrowscribbleBlack: string;
        avatarBlue: string;
        bellBlack: string;
        bellfilledBlack: string;
        benefitBlack: string;
        bestpriceBlack: string;
        bundleGreen: string;
        bundleWhite: string;
        calendarBlack: string;
        campsBlack: string;
        christmastreeBlack: string;
        christmastreeGreen: string;
        clickandcollectBlack: string;
        colors: string;
        deliveryBlack: string;
        deliverycostBlack: string;
        deliveryexpress: string;
        deliveryroundedBlack: string;
        deliveryryrBlack: string;
        discountBlack: string;
        drillBlack: string;
        easyshoppingBlue: string;
        ecomaterialBlack: string;
        ecoproductionBlack: string;
        educationBlack: string;
        eventsBlack: string;
        freereturn100Black: string;
        freereturn21Black: string;
        freereturnBlack: string;
        freeskiBlack: string;
        headsetBlack: string;
        headsetBlue: string;
        headsetWhite: string;
        jobsBlue: string;
        legalBlack: string;
        legalBlue: string;
        locationBlack: string;
        lockBlack: string;
        longboardBlack: string;
        mountainwave: string;
        orderBlue: string;
        paymentBlack: string;
        paymentBlue: string;
        phoneBlack: string;
        phoneWhite: string;
        pressBlack: string;
        pressBlue: string;
        quotationBlack: string;
        quotationWhite: string;
        recycleBlack: string;
        remoteBlack: string;
        returnBlack: string;
        returnBlue: string;
        returntoshopBlack: string;
        seasonalcardBlack: string;
        shop2Black: string;
        shopBlack: string;
        shopBlue: string;
        shoppingguideBlue: string;
        sizefinderBlack: string;
        sizefitlargeBlack: string;
        sizefitsmallBlack: string;
        sizeguideBlack: string;
        skateboardBlack: string;
        snowboardBlack: string;
        snowwearBlack: string;
        staffpickBlue: string;
        supportsslBlack: string;
        supportsslBlue: string;
        surfboardBlack: string;
        thirtyyearsBlack: string;
        tomatoBlack: string;
        tomatoBlue: string;
        tomatocheck: string;
        touringBlack: string;
        voucherBlack: string;
    };
};

export declare const Pagination: ForwardRefExoticComponent<HTMLAttributes<HTMLDivElement> & {
    disableNextButton?: boolean;
    disablePreviousButton?: boolean;
    infoText?: React.ReactNode;
    mainText?: React.ReactNode;
    onNextButtonClick?: () => void;
    onPreviousButtonClick?: () => void;
    progressBar?: number;
} & RefAttributes<HTMLDivElement>>;

declare type Props = {
    anchorSelect?: string;
    children?: React.ReactNode;
    variant?: "black" | "yellow";
};

export declare const RadioButton: ForwardRefExoticComponent<HTMLAttributes<HTMLDivElement> & {
    error?: React.ReactNode;
    inputProps?: React.InputHTMLAttributes<HTMLInputElement>;
} & RefAttributes<HTMLDivElement>>;

export declare const RangeSlider: ForwardRefExoticComponent<HTMLAttributes<HTMLDivElement> & {
    max?: number;
    min?: number;
    maxValue?: number;
    minValue?: number;
    onMaxValueChange?: (value: number) => void;
    onMinValueChange?: (value: number) => void;
    placeholderMax?: string;
    placeholderMin?: string;
    rangeText?: React.ReactNode;
    resultText?: React.ReactNode;
    symbol?: string;
} & RefAttributes<HTMLDivElement>>;

export declare const SizeButton: ForwardRefExoticComponent<ButtonHTMLAttributes<HTMLButtonElement> & {
    active?: boolean;
    disabled?: boolean;
    iconLeft?: IconProp_2;
    iconRight?: IconProp_2;
} & RefAttributes<HTMLButtonElement>>;

declare type Styles = {
    white: "#ffffff";
    grey1: "#333333";
    grey2: "#8f8f8f";
    grey3: "#cccccc";
    grey4: "#f4f4f4";
    yellow1: "#ffde00";
    yellow2: "#ffed73";
    yellow3: "#fff5b3";
    yellow4: "#fffad9";
    red1: "#ff4444";
    red2: "#ff9898";
    red3: "#ffc7c7";
    red4: "#ffe3e3";
    sky1: "#0099cc";
    sky2: "#73c7e3";
    sky3: "#b3e0f0";
    sky4: "#d9f0f7";
    blue1: "#2d69aa";
    blue2: "#8cadd0";
    blue3: "#c0d2e6";
    blue4: "#e0e9f1";
    petrol1: "#2fa9b4";
    petrol2: "#8dd0d6";
    petrol3: "#c1e5e9";
    petrol4: "#e0f2f4";
    mint1: "#21cdab";
    mint2: "#8ee4d1";
    mint3: "#c2f0e6";
    mint4: "#e0f8f2";
    green1: "#24a779";
    green2: "#87cfb5";
    green3: "#bde5d7";
    green4: "#def2eb";
    cyprus2: "#84a2a5";
    cyprus3: "#bcccce";
    olive2: "#b4c3b8";
    olive3: "#d6ded8";
    almond2: "#eee6e3";
    almond3: "#f6f1f0";
    purple2: "#aeaed2";
    purple3: "#d1d1e6";
    redpurple2: "#d59cd3";
    redpurple3: "#e8c9e7";
    rustyred2: "#d06f82";
    rustyred3: "#e8b7c0";
    coral2: "#ee7766";
    coral3: "#f9ccc6";
    lemonlime2: "#c1d301";
    lemonlime3: "#e9f84e";
    space4: "4px";
    space8: "8px";
    space16: "16px";
    space24: "24px";
    space32: "32px";
    space40: "40px";
    space48: "48px";
    space64: "64px";
};

export declare const styles: Styles;

export declare const Tooltip: ForwardRefExoticComponent<Props & RefAttributes<TooltipRefProps>>;

export { }
